### ISSUE TITLE
socket.send() raised exception.

### ISSUE THREAD

**Issue by jpmaligne** [allan-simon/mock-amqp-server#5]
When I try to call

```
self.post(
    BASE_URL + '/add-message-on/' + EXCHANGE,
    json={
        'headers': message_headers,
        'body': message_body,
    }
)
```

A `docker logs -f` on the rabbitmq container prints a lot of 
`socket.send() raised exception.`

**Comment by allan-simon** [comment]
https://github.com/python/cpython/blob/fb2c3465f09e1f720cdae7eca87d62125a327fd9/Lib/asyncio/selector_events.py#L985 for where does the message come from, 

fixed by  861f74c
